import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const filePath = path.join(__dirname, 'src/data/capitulos.js');
let content = fs.readFileSync(filePath, 'utf8');

// Insert additional paragraphs before each chapter's contenido closing backtick+comma
// The closing backtick+comma is on the last line of the contenido string.

const expansions = {
  1: `\n\nPoco a poco, aquellos encuentros digitales se convirtieron en el ritual más esperado de mis días. No existía agenda que pudiera competir con la emoción de saber que pronto escucharía su voz o leería sus palabras. Lo demás podía esperar, pero ella no. Ella se había convertido en mi prioridad sin habérmelo propuesto, de una manera tan natural que apenas lo noté hasta que ya era demasiado tarde para dar marcha atrás.\n\nRecuerdo la textura de sus palabras, la forma en que hilaba sus ideas con una claridad que me dejaba sin aliento. Podía pasar horas escuchándola hablar de cualquier cosa, porque su voz tenía el poder de transformar lo ordinario en extraordinario. No importaba si hablaba de sus sueños más profundos o de algo tan simple como lo que había comido ese día; todo sonaba fascinante cuando salía de sus labios.\n\nCon cada día que pasaba, me convencía más de que aquello no era una casualidad. El universo nos había puesto en el mismo camino por una razón, y aunque todavía no entendía cuál era, estaba dispuesto a descubrirlo. Estaba dispuesto a seguir ese hilo invisible que nos conectaba, sin importar a dónde nos llevara.\n\nHoy, al recordar aquellos primeros días, me doy cuenta de que el amor no siempre llega con grandes señales ni anuncios rimbombantes. A veces llega en silencio, a través de una pantalla, en medio de una conversación que parecía no llevar a ningún lado. Pero cuando llega de verdad, lo reconoces porque todo cambia. El mundo se vuelve más brillante, los colores más vivos, y cada día tiene un nuevo motivo para ser vivido.\n\nCada conversación era un mundo nuevo por descubrir. Me fascinaba la forma en que su mente funcionaba, la manera en que conectaba ideas que a mí nunca se me habrían ocurrido, la profundidad con la que analizaba las situaciones. No era solo inteligente, era brillante de una manera única. Y yo, sin darme cuenta, me estaba enamorando no solo de quien era, sino de la forma en que veía el mundo.\n\nA veces me quedaba despierto hasta tarde, después de que ella se durmiera, repasando mentalmente cada detalle de nuestra conversación. Sonreía como un tonto recordando sus ocurrencias, sus comentarios ingeniosos, la forma en que podía pasar de una profunda reflexión filosófica a un chiste absurdo en cuestión de segundos. Esa versatilidad, esa capacidad de ser tan compleja y tan simple al mismo tiempo, me tenía completamente cautivado.\n\nY en medio de todo eso, comenzaba a formarse una certeza que crecía con cada día que pasaba: esto no era un juego ni una distracción pasajera. Esto era real. Y daba miedo, porque era la primera vez que sentía algo tan intenso, pero también era emocionante porque sabía, en el fondo, que estaba viviendo algo que recordaría para siempre.`,
  2: `\n\nHabía momentos en los que la distancia se hacía insoportable, no porque fuera física, sino porque el deseo de tenerla cerca superaba cualquier barrera que pudiera imaginar. Quería verla, tocarla, confirmar que no era un sueño del que pudiera despertar en cualquier momento. Quería demostrarle con gestos lo que las palabras se quedaban cortas para expresar.\n\nPero también aprendí a valorar la belleza de lo que teníamos. No todo en el amor necesita ser físico para ser real. Hay conexiones que trascienden lo material, que se alimentan de palabras, de miradas a través de una cámara, de silencios compartidos a pesar de la distancia. Nuestra conexión era de esas, de las que no entienden de kilómetros ni de husos horarios.\n\nComencé a guardar cada detalle como quien colecciona tesoros: la forma en que pronunciaba mi nombre, el brillo en sus ojos cuando hablaba de lo que le apasionaba, la manera en que su risa llenaba el silencio de la noche. Eran pequeños fragmentos de felicidad que iba acumulando sin darme cuenta, construyendo un mosaico de momentos que sería imposible olvidar.\n\nY cuando finalmente llegaba la noche y tenía que despedirme, lo hacía con la promesa silenciosa de que al día siguiente volvería a estar ahí, esperando su mensaje, deseando escuchar su voz, amando cada instante que pudiera compartir con ella. Porque ella se había convertido no solo en alguien importante, sino en la razón por la que cada día valía la pena ser vivido.\n\nComencé a notar que las canciones románticas que antes ignoraba ahora tenían un significado especial. Cada letra parecía escrita para nosotros, cada melodía parecía describir lo que sentía. Era como si el universo entero estuviera conspirando para recordarme constantemente lo que estaba sintiendo, como si no quisiera dejar que olvidara ni por un segundo la magnitud de lo que estaba ocurriendo.\n\nA veces me asustaba la intensidad de mis propios sentimientos. No estaba acostumbrado a sentir tanto, a desear tanto, a necesitar tanto de alguien. Pero al mismo tiempo, no podía negar que esa intensidad era lo que hacía que todo valiera la pena. Prefería sentir demasiado a no sentir nada. Prefería arriesgarme a salir lastimado a vivir en la seguridad vacía de no haberlo intentado.`,
  3: `\n\nEn la soledad de sus noches, cuando los recuerdos se agolpaban sin piedad, el chico repasaba una y otra vez las palabras que había pronunciado. Las analizaba desde todos los ángulos posibles, buscando una interpretación diferente, una manera de haber dicho las cosas que no hubiera llevado al mismo desenlace. Pero no importaba cuánto lo intentara, el resultado siempre era el mismo: había fallado en el momento más importante.\n\nLo que más dolor le causaba no era tanto haberla perdido, sino saber que ella había sido lo suficientemente valiente para abrir su corazón, para exponerse al rechazo, para ser vulnerable frente a él. Y él, en lugar de corresponder a esa valentía con la suya propia, había optado por la cobardía, por el camino más fácil, por la salida que evitaba el riesgo pero que también cerraba la puerta a la felicidad.\n\nComenzó a escribir cartas que nunca enviaría, palabras que quemaban el papel pero que necesitaba sacar de su interior. En cada carta le explicaba lo que realmente sentía, le confesaba sus miedos, le prometía que si pudiera volver atrás las cosas serían diferentes. Pero las cartas se acumulaban en un cajón, como testigos mudos de un amor que no había tenido el valor de defenderse a sí mismo.\n\nAprendió que el arrepentimiento es el precio que se paga por las decisiones que no se toman, por las palabras que no se dicen, por los riesgos que no se corren. Y decidió que, si alguna vez la vida le daba una segunda oportunidad, no volvería a cometer el mismo error. Estaría listo. Sería valiente. Porque había aprendido que el amor no espera a que estemos preparados; sencillamente ocurre, y cuando ocurre, hay que estar a su altura.\n\nCada vez que veía su nombre aparecer en la pantalla, su corazón daba un vuelco seguido de un dolor punzante al recordar lo que había hecho. Era una mezcla confusa de alegría por saber de ella y tristeza por saber que él era la causa de su distancia. Aprendió a convivir con esa dualidad, con ese constante tira y afloja entre el deseo y el arrepentimiento.\n\nPero también descubrió algo importante en medio de todo aquel dolor: el amor verdadero no desaparece cuando se cometen errores. El amor verdadero duele, pero también enseña. Y aunque había herido a la persona que más amaba, ese amor seguía siendo la fuerza más poderosa dentro de él. No iba a rendirse. No podía rendirse. Porque rendirse significaría aceptar que nunca mereció su amor, y eso era algo que no estaba dispuesto a aceptar.\n\nSe aferró a esa esperanza como un náufrago se aferra a una tabla en medio del océano. Era frágil, era incierta, pero era todo lo que tenía. Y mientras esa esperanza existiera, mientras hubiera una mínima posibilidad de redención, seguiría luchando. No por orgullo, no por obsesión, sino porque el amor que sentía merecía esa lucha.`,
  4: `\n\nEl día que ella le confesó que había seguido adelante con su vida, que había conocido a alguien más, el mundo se detuvo para él. No era algo que no hubiera imaginado, pero escucharlo de sus labios fue como recibir una puñalada directa al corazón. Ella merecía ser feliz, lo sabía, pero eso no hacía el dolor más llevadero.\n\nEn ese momento comprendió que el amor no es un derecho que se gana, sino un regalo que se recibe. Y él había desechado ese regalo cuando lo tuvo en sus manos. Ahora solo le quedaba aceptar las consecuencias de sus actos y aprender a vivir con ellas.\n\nPero también entendió algo más: el amor que sentía por ella no desaparecería solo porque ella estuviera con otra persona. El amor no funciona así. El amor verdadero perdura más allá de las circunstancias, más allá de la distancia, más allá del tiempo. Y aunque ya no pudieran estar juntos, agradecía haberla conocido, haber sentido algo tan profundo que lo había transformado para siempre.\n\nSe prometió a sí mismo que no dejaría que aquella experiencia lo amargara. En lugar de eso, la usaría como combustible para convertirse en la mejor versión de sí mismo. Porque si ella había visto algo valioso en él, entonces él debía estar a la altura de esa visión. Debía convertirse en alguien de quien ella pudiera sentirse orgullosa, aunque ya no estuvieran juntos.\n\nLos días siguientes fueron un ejercicio constante de aceptación. Aceptar que había perdido, aceptar que ella tenía derecho a seguir adelante, aceptar que sus decisiones tenían consecuencias. No fue fácil, hubo momentos en los que quería rendirse, en los que el dolor era tan grande que le costaba respirar. Pero siguió adelante, un paso a la vez.\n\nComenzó a escribir un diario, no para enviarle cartas que nunca leería, sino para entenderse a sí mismo. Para desentrañar los nudos emocionales que lo habían llevado a tomar las decisiones que tomó. Para comprenderse mejor y así poder cambiar. Porque si algo había aprendido de todo aquello era que el cambio verdadero comenzaba desde adentro, no desde las circunstancias externas.\n\nY mientras escribía, mientras se enfrentaba a sus propios demonios, comenzó a notar pequeños cambios en sí mismo. Las heridas seguían ahí, pero ya no sangraban como antes. El recuerdo de ella seguía presente, pero ya no era una fuente de dolor sino de enseñanza. Lentamente, casi sin darse cuenta, estaba sanando.`,
  5: `\n\nLos años de ausencia no mitigaron el recuerdo de su sonrisa, ni borraron la calidez de su mirada. Al contrario, el tiempo actuó como un afinador de memoria, haciendo que los momentos vividos cobraran una nitidez sorprendente. Las imágenes se volvieron más claras, los sentimientos más puros, como si el paso del tiempo hubiera decantado lo esencial y eliminado lo superfluo.\n\nAprendió a vivir con la ausencia sin dejar que esta definiera su existencia. Había días en los que el recuerdo de ella llegaba con una intensidad que lo desarmaba por completo, y otros en los que lograba mantenerlo a raya, como un visitante ocasional al que se atiende pero no se le permite quedarse. Pero siempre, en el fondo, estaba ahí.\n\nComenzó a entender que algunas personas llegan a nuestra vida para quedarse, aunque físicamente no estén presentes. Se convierten en parte de nosotros, en experiencias que nos moldean, en enseñanzas que nos acompañan. Ella era eso para él: una huella imborrable que el tiempo no podía borrar.\n\nY quizás por eso, cuando menos lo esperaba, cuando había aceptado que su historia había terminado, el destino decidió cruzar sus caminos una vez más. Porque algunas historias no están hechas para terminar, sino para hacer una pausa, para dar tiempo a que sus protagonistas crezcan, aprendan y estén listos para el siguiente capítulo.\n\nDurante aquellos años de separación, el chico había cambiado. No era la misma persona que había cometido el error. Había crecido, había aprendido, había sanado muchas de sus heridas. Y cuando volvió a encontrarse con ella, se dio cuenta de que el amor seguía ahí, intacto, esperando pacientemente su momento.\n\nNo fue un reencuentro planeado ni esperado. Ocurrió de manera natural, como si el universo hubiera estado orquestando ese momento desde el principio. Y cuando sus miradas se encontraron, supo que nada había cambiado realmente. El amor que sentía por ella seguía siendo el mismo, solo que ahora estaba acompañado de una sabiduría que antes no tenía.\n\nEsa sabiduría le dijo que no podía apresurarse, que debía dejar que las cosas fluyeran de manera natural. Que esta vez no podía forzar nada, sino permitir que la vida hiciera su trabajo. Y aunque la impaciencia lo consumía por dentro, aprendió a esperar, a confiar, a tener fe en que si algo tenía que ser, sería.`,
  6: `\n\nHubo un momento, justo cuando el reencuentro se produjo, en el que todo pareció detenerse. Las palabras sobraban porque los ojos hablaban por sí solos. Había tanto que decir y al mismo tiempo nada que añadir, porque en esa mirada se resumían años de sentimientos guardados, de momentos compartidos y de una conexión que el tiempo no había logrado romper.\n\nElla también había cambiado. Se había convertido en una mujer más fuerte, más segura, más dueña de sí misma. Y él, al verla, sintió un orgullo inmenso de la persona en la que se había transformado. Porque aunque él no hubiera estado presente en su proceso, de alguna manera se sentía parte de su historia, de su crecimiento, de su camino.\n\nLas primeras conversaciones fueron cuidadosas, como quien pisa terreno desconocido. Ambos medían sus palabras, evitando tocar las heridas del pasado, construyendo puentes sobre los escombros de lo que había sido destruido. Pero pronto descubrieron que la conexión seguía ahí, intacta, esperando el momento adecuado para resurgir.\n\nY cuando finalmente hablaron del pasado, de los errores cometidos, de las oportunidades perdidas, lo hicieron con una madurez que antes no tenían. Ya no había culpas ni reproches, solo la comprensión de que ambas habían hecho lo mejor que podían en cada momento. Y esa comprensión fue el primer paso hacia una nueva oportunidad, hacia un nuevo comienzo.\n\nLo que siguió fue un baile delicado entre el deseo de avanzar rápido y la necesidad de ir despacio. Ambos sabían que tenían algo especial entre manos, algo que merecía ser cuidado con paciencia. No querían repetir los errores del pasado, así que decidieron tomarlo con calma, reconstruyendo la confianza paso a paso.\n\nCada mensaje, cada llamada, cada encuentro era una oportunidad para conocerse de nuevo. Para descubrir cómo habían cambiado, qué nuevas capas había adquirido su personalidad, qué sueños nuevos habían nacido en ellos. Era como volver a enamorarse, pero esta vez con el beneficio de conocer de antemano la profundidad de lo que podían construir juntos.\n\nY en ese proceso de redescubrimiento, ambos se dieron cuenta de que el tiempo no había debilitado su conexión, sino que la había purificado. Lo superfluo había desaparecido, quedando solo lo esencial. Y lo esencial era que se amaban, que siempre se habían amado, y que estaban dispuestos a hacer lo que fuera necesario para no volver a perder esa oportunidad.`,
  7: `\n\nLa decisión que tomó aquel día lo persiguió durante mucho tiempo. No como un fantasma que atormenta, sino como una sombra que recuerda lo que se puede perder cuando el miedo gobierna. Cada vez que cerraba los ojos, veía su rostro, la expresión de decepción que había cruzado por su mirada cuando él le dijo que no podía estar con ella.\n\nPero el tiempo, ese maestro implacable, le enseñó que los errores no definen a una persona. Lo que realmente define es lo que se hace después del error. Si se aprende de él, si se crece, si se transforma el dolor en sabiduría. Y él estaba decidido a que aquel error no fuera en vano.\n\nSe sumergió en un proceso de autoconocimiento que nunca antes había emprendido. Comenzó a hacerse preguntas incómodas, a confrontar sus miedos más profundos, a desmantelar las barreras que había construido alrededor de su corazón. No fue fácil, ni rápido, pero era necesario.\n\nY mientras trabajaba en sí mismo, una idea comenzó a tomar forma en su mente: si alguna vez tenía la oportunidad de demostrar que había cambiado, no la desperdiciaría. Estaría preparado para ser el hombre que ella merecía, el que siempre debió haber sido. Porque el amor, cuando es verdadero, no solo transforma a quien lo recibe, sino también a quien lo da.\n\nCada paso en su proceso de crecimiento personal lo acercaba más a entender las razones detrás de sus miedos. Descubrió que su temor al compromiso no había nacido de la nada, sino que era el resultado de experiencias pasadas que lo habían marcado. Y aunque entender el origen del miedo no lo hacía desaparecer mágicamente, le daba las herramientas para enfrentarlo.\n\nAprendió técnicas para manejar la ansiedad cuando esta aparecía, desarrolló la capacidad de identificar cuándo sus decisiones estaban siendo influenciadas por el miedo en lugar del amor, y practicó la comunicación honesta incluso cuando le resultaba incómoda. Cada pequeño avance era una victoria, cada momento de claridad lo motivaba a seguir adelante.\n\nEl proceso fue largo y a menudo solitario, pero necesario. Porque sabía que no podía pedirle a nadie que lo amara si él mismo no se amaba lo suficiente como para enfrentar sus propios demonios. Y aunque el camino era difícil, cada paso lo acercaba más a la persona que quería ser.`,
  8: `\n\nA veces, en los momentos más inesperados, cuando la música sonaba o el viento soplaba de cierta manera, él sentía su presencia como si estuviera realmente allí. No era una alucinación ni un deseo, sino la certeza de que las personas que amamos dejan una marca energética en nosotros que trasciende lo físico.\n\nComenzó a ver señales en todas partes. Una canción que ella solía cantar sonaba justo cuando más la necesitaba. Un lugar que habían visitado juntos aparecía en sus sueños. Pequeñas coincidencias que alimentaban su esperanza de que, de alguna manera, el universo los mantenía conectados.\n\nY quizás eso era suficiente. Quizás no necesitaba tenerla físicamente a su lado para seguir amándola. El amor que sentía por ella era real, había sido real, y eso era algo que nadie podía quitarle. Había amado con toda su alma, y ese amor seguía vivo dentro de él, independientemente de las circunstancias externas.\n\nAprendió a encontrar paz en esa certeza. Dejó de luchar contra sus sentimientos y comenzó a aceptarlos como parte de quien era. El amor que sentía por ella no era una debilidad ni una carga, sino una prueba de que era capaz de sentir profundamente. Y esa capacidad, en un mundo donde las conexiones son cada vez más superficiales, era un don que debía atesorar.\n\nLos días se convirtieron en semanas, las semanas en meses, y los meses en un año, luego dos, luego tres. El dolor se fue transformando en una especie de nostalgia melancólica, como la que se siente al recordar un lugar hermoso que visitaste y sabes que probablemente no volverás a ver. Pero incluso esa nostalgia era mejor que no tener ningún recuerdo.\n\nA veces imaginaba cómo sería su vida si las cosas hubieran sido diferentes. Se visualizaba caminando a su lado, compartiendo un café, viendo el atardecer juntos. Eran imágenes borrosas, como fotografías antiguas, pero le traían una paz inexplicable.\n\nCon el tiempo, esas imágenes dejaron de causarle dolor y comenzaron a causarle gratitud. Gratitud por haber conocido a alguien que valía la pena recordar, gratitud por haber experimentado un amor tan profundo, gratitud por todas las enseñanzas que esa relación le había dejado. Y en esa gratitud, encontró la fuerza para seguir adelante sin rencor, sin amargura, con el corazón abierto a lo que el futuro pudiera traerle.`,
  9: `\n\nLentamente, los muros que habíamos construido alrededor de nuestros corazones comenzaron a derrumbarse. No de golpe, sino ladrillo por ladrillo, en un proceso que requería paciencia y confianza. Cada confesión, cada lágrima compartida, cada momento de vulnerabilidad nos acercaba un paso más hacia la sanación.\n\nElla me mostró que el perdón no es un acto de debilidad, sino de fortaleza. Que perdonar no significa justificar el daño recibido, sino liberarse del peso del rencor para poder seguir adelante. Y yo aprendí a perdonarme a mí mismo, a aceptar que había cometido errores pero que no estaba condenado a repetirlos.\n\nJuntos descubrimos que las segundas oportunidades son un regalo que hay que honrar con acciones, no solo con palabras. Que decir "lo siento" es fácil, pero demostrar que realmente lo sientes requiere un compromiso diario, una dedicación constante a ser mejor que el día anterior.\n\nY aunque el camino no era fácil, aunque había días en los que el dolor del pasado parecía insuperable, seguíamos adelante. Porque habíamos descubierto que nuestro amor era más fuerte que nuestras heridas. Que merecía la pena luchar por él. Que juntos podíamos construir algo que ninguno de los dos podría haber construido por separado.\n\nCada pequeño gesto de confianza era una victoria. Cada vez que ella compartía algo que le preocupaba sin miedo a mi reacción, celebrábamos ese avance. Cada vez que yo lograba estar presente emocionalmente cuando ella me necesitaba, sabía que estábamos sanando algo importante.\n\nNo fue lineal. Hubo recaídas, momentos en los que las dudas regresaban con fuerza y parecía que estábamos retrocediendo. Pero aprendimos que las recaídas no significaban fracaso, sino que eran parte natural del proceso de sanación. Lo importante era no rendirse, seguir avanzando aunque fuera a pasos pequeños.\n\nY en ese proceso, algo hermoso comenzó a suceder. Las heridas que antes nos separaban comenzaron a convertirse en puentes. Cada cicatriz compartida nos unía más, porque entendíamos el dolor del otro de una manera que solo quienes han sufrido juntos pueden entender. Y ese entendimiento mutuo se convirtió en la base más sólida sobre la que podíamos construir nuestro futuro.`,
  10: `\n\nEl momento en que le mostré el proyecto que había creado para ella fue uno de los más significativos de mi vida. Había puesto en él cada gramo de amor que llevaba dentro, cada recuerdo, cada deseo, cada esperanza. Era mi corazón hecho código, mi alma traducida a píxeles y palabras.\n\nVer sus ojos recorrer cada página, cada detalle, cada elemento diseñado especialmente para ella, fue una experiencia que ninguna palabra podría describir adecuadamente. En ese momento, todo el tiempo invertido, todas las horas de trabajo, todas las dudas superadas, cobraron sentido. Verla emocionarse era la recompensa más grande que podía recibir.\n\nPero lo que más me impactó no fue su reacción inicial, sino lo que vino después. Comenzó a visitar la página regularmente, a descubrir nuevos detalles que había escondido para que ella los encontrara, a conectarse con cada canción y cada palabra de una manera que superaba todas mis expectativas.\n\nEn ese momento comprendí que el amor no se trata solo de sentir, sino de crear. De construir espacios donde ese amor pueda habitar, de diseñar experiencias que lo alimenten, de dejar huellas que demuestren que es real. Y yo había creado algo para ella, algo que la acompañaría siempre, algo que sería un recordatorio permanente de cuánto significaba para mí.\n\nCada detalle del proyecto tenía un significado especial. Los colores elegidos no eran al azar, sino que representaban momentos importantes de nuestra historia. Las canciones seleccionadas no eran simplemente canciones que me gustaban, sino la banda sonora de los momentos que habíamos compartido. Cada elemento estaba impregnado de intención y amor.\n\nTrabajar en ello me permitió canalizar todos mis sentimientos de una manera constructiva. En lugar de quedarme atrapado en la ansiedad de no saber cómo expresar lo que sentía, encontré un medio para hacerlo. El proyecto se convirtió en mi lenguaje de amor, en la forma más auténtica que encontré para decirle todo aquello que las palabras se quedaban cortas para expresar.\n\nY al verla conectarse con cada parte de ese proyecto, supe que había logrado mi objetivo. Había encontrado la manera de hacerle sentir, aunque fuera por un momento, la magnitud de lo que significaba para mí. Y eso, más que cualquier otra cosa, era lo que siempre había querido: que ella supiera, sin lugar a dudas, cuánto la amaba.`,
  11: `\n\nCon el tiempo, aprendimos a leer nuestras heridas sin juzgarlas. Dejamos de verlas como enemigas y comenzamos a entenderlas como maestras que nos enseñaban lo que necesitábamos sanar. Cada gatillo emocional, cada reacción desproporcionada, cada momento de tensión era una señal de que había algo dentro de nosotros que todavía necesitaba atención y cuidado.\n\nDesarrollamos un lenguaje propio para comunicar nuestros estados emocionales sin culpar al otro. Aprendimos a decir "necesito espacio" sin que sonara a rechazo, y "necesito que estés cerca" sin que sonara a dependencia. Encontramos el equilibrio entre la independencia y la unión, entre ser individuos y ser pareja.\n\nLas crisis dejaron de ser amenazas y se convirtieron en oportunidades de crecimiento. Cuando surgía un conflicto, en lugar de distanciarnos, nos acercábamos. En lugar de buscar culpables, buscábamos soluciones. En lugar de guardar rencor, practicábamos el perdón.\n\nY así, día tras día, construimos una relación que no se basaba en la perfección, sino en la autenticidad. Una relación donde podíamos ser nosotros mismos sin miedo al rechazo, donde nuestras imperfecciones no eran defectos que ocultar, sino partes de nosotros que integrar y aceptar. Y eso, más que cualquier gesto grandioso, era la verdadera prueba de nuestro amor.\n\nRecuerdo una noche en particular, después de una discusión difícil, en la que ambos estábamos sentados en silencio, procesando lo que había ocurrido. En lugar de irnos a dormir enojados, como solíamos hacer antes, decidimos quedarnos ahí, en la incomodidad del momento, hasta encontrar una solución. No fue fácil, requirió mucha vulnerabilidad y honestidad, pero al final salimos más fuertes.\n\nEsa noche comprendí que el amor no se trata de evitar los conflictos, sino de atravesarlos juntos. Que una discusión no es el fin de una relación, sino una oportunidad para conocer mejor al otro y fortalecer los lazos que nos unen. Que el silencio después de una pelea no tiene por qué ser frío, sino que puede ser un espacio de reflexión compartida.\n\nAprendimos a pelear limpio. A expresar nuestro enojo sin atacar al otro, a comunicar nuestra frustración sin culpar, a pedir lo que necesitábamos sin exigir. Fue un aprendizaje constante, un músculo que fuimos fortaleciendo con cada conflicto superado. Y con el tiempo, las peleas se volvieron menos frecuentes y más constructivas.`,
  12: `\n\nHoy, al escribir estas palabras, siento que cada una de ellas carga con el peso y la belleza de todo lo vivido. No son solo letras sobre un papel, sino pedazos de mi alma que he ido depositando a lo largo de este viaje. Cada párrafo contiene una parte de mí que he descubierto gracias a ti, una lección que he aprendido a tu lado, un momento que hemos compartido y que se ha vuelto eterno.\n\nMi amor por ti no es el mismo que era al principio. Es más profundo, más paciente, más sabio. Ha sobrevivido a tormentas que habrían destruido amores más frágiles, ha atravesado desiertos de silencio y ha florecido en primaveras de renovación. Y cada etapa, cada fase, cada transformación, lo ha hecho más fuerte, más real, más nuestro.\n\nCuando pienso en el futuro, no lo hago con miedo sino con emoción. Porque sé que pase lo que pase, estaremos juntos. No porque el destino lo haya escrito, sino porque nosotros lo hemos elegido. Nos hemos elegido en la oscuridad y en la luz, en la certeza y en la duda, en la salud y en la enfermedad emocional.\n\nY mientras tenga vida, mientras me quede aliento, mientras mi corazón siga latiendo, te elegiré a ti. Una y otra vez. En esta vida y en todas las que vengan. Porque no hay amor más grande que aquel que se elige conscientemente cada día, y yo elijo amarte hoy, mañana y siempre.\n\nHe aprendido que el amor no es un destino, sino un viaje. Que no se trata de llegar a algún lugar, sino de disfrutar el camino recorrido juntos. Y en este viaje, tú has sido mi mejor compañera, mi guía en los momentos de oscuridad, mi luz en los días de tormenta. No puedo imaginar recorrer este camino con nadie más.\n\nCada día a tu lado es un recordatorio de que los finales felices no existen, porque las historias de amor verdaderas no terminan. Se transforman, evolucionan, se profundizan con el tiempo. Y nuestra historia, la nuestra, sigue escribiéndose cada día, página a página, con la tinta indeleble de un amor que ha demostrado ser más fuerte que cualquier obstáculo.\n\nGracias por cada sonrisa, por cada abrazo, por cada momento compartido. Gracias por las lágrimas que lloramos juntos y por las risas que compartimos. Gracias por enseñarme que merezco ser amado y por mostrarme cómo amar de verdad. Gracias por ser tú, simplemente tú, la persona más maravillosa que la vida ha puesto en mi camino.\n\nTe amo. Y te amaré siempre. En esta vida y en todas las que vengan.`
};


// Process each chapter
for (let id = 1; id <= 12; id++) {
  const exp = expansions[id];
  if (!exp) continue;
  
  // Find the closing backtick+comma for this chapter's contenido
  // We need to match the Nth occurrence of backtick+comma pattern
  // The chapters are ordered by id, so the Nth contenido close corresponds to chapter N
  
  let count = 0;
  let pos = 0;
  const regex = /`,/g;
  let match;
  
  while ((match = regex.exec(content)) !== null) {
    count++;
    if (count === id) {
      pos = match.index;
      break;
    }
  }
  
  if (pos > 0) {
    // Insert expansion text right before the closing backtick+comma
    content = content.slice(0, pos) + exp + '\n' + content.slice(pos);
    console.log(`Chapter ${id}: expanded at position ${pos}`);
  } else {
    console.log(`Chapter ${id}: not found!`);
  }
}

fs.writeFileSync(filePath, content, 'utf8');
console.log('\nDone!');
